name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
        
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm cache clean --force
        rm -rf node_modules package-lock.json
        npm install
        npm run-script build
      working-directory: ${{env.working-directory}}
      env:
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
        REACT_APP_DATABASE_URL: ${{ secrets.REACT_APP_DATABASE_URL }}
        REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
        REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
        REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
        REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}

    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KEY }}
        BRANCH: gh-pages
        FOLDER: dist
